// Language data for "How to Say F*ck You Around the World"
const languageData = [
    {
        id: "english",
        country: "United States",
        countryCode: "US",
        languageName: "English",
        phrase: "Fuck you",
        pronunciation: "fuhk yoo",
        audioFile: "audio/english.mp3",
        memeReference: "images/english-meme.jpg",
        funFact: "One of the most versatile words in English, 'fuck' can be used as a verb, noun, adjective, and more!"
    },
    {
        id: "spanish",
        country: "Spain",
        countryCode: "ES",
        languageName: "Spanish",
        phrase: "Que te jodan",
        pronunciation: "keh teh HO-dan",
        audioFile: "audio/spanish.mp3",
        memeReference: "images/spanish-meme.jpg",
        funFact: "In Spain, they might add 'gilipollas' for extra emphasis!"
    },
    {
        id: "french",
        country: "France",
        countryCode: "FR",
        languageName: "French",
        phrase: "Va te faire foutre",
        pronunciation: "vah tuh fair FOO-truh",
        audioFile: "audio/french.mp3",
        memeReference: "images/french-meme.jpg",
        funFact: "The French have a reputation for being romantic, but they can curse with the best of them!"
    },
    {
        id: "german",
        country: "Germany",
        countryCode: "DE",
        languageName: "German",
        phrase: "Fick dich",
        pronunciation: "fik dikh",
        audioFile: "audio/german.mp3",
        memeReference: "images/german-meme.jpg",
        funFact: "German insults sound extra angry due to the language's harsh consonants!"
    },
    {
        id: "italian",
        country: "Italy",
        countryCode: "IT",
        languageName: "Italian",
        phrase: "Vaffanculo",
        pronunciation: "vah-fan-KOO-loh",
        audioFile: "audio/italian.mp3",
        memeReference: "images/italian-meme.jpg",
        funFact: "Italians often accompany this phrase with the 'umbrella' hand gesture for extra effect!"
    },
    {
        id: "portuguese",
        country: "Portugal",
        countryCode: "PT",
        languageName: "Portuguese",
        phrase: "Vai se foder",
        pronunciation: "vye see fo-DEHR",
        audioFile: "audio/portuguese.mp3",
        memeReference: "images/portuguese-meme.jpg",
        funFact: "In Brazil, they might say 'Vai tomar no cu' instead!"
    },
    {
        id: "russian",
        country: "Russia",
        countryCode: "RU",
        languageName: "Russian",
        phrase: "Иди на хуй",
        pronunciation: "ee-DEE nah hooy",
        audioFile: "audio/russian.mp3",
        memeReference: "images/russian-meme.jpg",
        funFact: "Russian profanity (mat) is so elaborate it's almost an art form!"
    },
    {
        id: "japanese",
        country: "Japan",
        countryCode: "JP",
        languageName: "Japanese",
        phrase: "くたばれ",
        pronunciation: "ku-ta-ba-re",
        audioFile: "audio/japanese.mp3",
        memeReference: "images/japanese-meme.jpg",
        funFact: "Japanese people rarely use direct insults, making this phrase extra shocking when used!"
    },
    {
        id: "mandarin",
        country: "China",
        countryCode: "CN",
        languageName: "Mandarin Chinese",
        phrase: "去你妈的",
        pronunciation: "qù nǐ mā de",
        audioFile: "audio/mandarin.mp3",
        memeReference: "images/mandarin-meme.jpg",
        funFact: "Most Chinese insults involve your mother or ancestors!"
    },
    {
        id: "korean",
        country: "South Korea",
        countryCode: "KR",
        languageName: "Korean",
        phrase: "씨발",
        pronunciation: "shi-bal",
        audioFile: "audio/korean.mp3",
        memeReference: "images/korean-meme.jpg",
        funFact: "This word is so taboo in Korea that it's often censored in media as 'S-bal'!"
    },
    {
        id: "arabic",
        country: "Saudi Arabia",
        countryCode: "SA",
        languageName: "Arabic",
        phrase: "كس أمك",
        pronunciation: "kuss ummak",
        audioFile: "audio/arabic.mp3",
        memeReference: "images/arabic-meme.jpg",
        funFact: "Arabic insults vary widely across different regions and dialects!"
    },
    {
        id: "hindi",
        country: "India",
        countryCode: "IN",
        languageName: "Hindi",
        phrase: "अपनी गांड मरा",
        pronunciation: "apni gaand mara",
        audioFile: "audio/hindi.mp3",
        memeReference: "images/hindi-meme.jpg",
        funFact: "Bollywood movies often use creative euphemisms to avoid direct profanity!"
    },
    {
        id: "turkish",
        country: "Turkey",
        countryCode: "TR",
        languageName: "Turkish",
        phrase: "Siktir git",
        pronunciation: "sick-teer git",
        audioFile: "audio/turkish.mp3",
        memeReference: "images/turkish-meme.jpg",
        funFact: "Turkish has a wide variety of colorful insults involving animals!"
    },
    {
        id: "dutch",
        country: "Netherlands",
        countryCode: "NL",
        languageName: "Dutch",
        phrase: "Krijg de klere",
        pronunciation: "krayg duh KLAY-ruh",
        audioFile: "audio/dutch.mp3",
        memeReference: "images/dutch-meme.jpg",
        funFact: "Dutch people often use diseases in their insults, like 'krijg de typhus' (get typhoid)!"
    },
    {
        id: "swedish",
        country: "Sweden",
        countryCode: "SE",
        languageName: "Swedish",
        phrase: "Dra åt helvete",
        pronunciation: "drah oht HELL-veh-teh",
        audioFile: "audio/swedish.mp3",
        memeReference: "images/swedish-meme.jpg",
        funFact: "Swedes are usually polite, but their swear words can be quite creative!"
    },
    {
        id: "polish",
        country: "Poland",
        countryCode: "PL",
        languageName: "Polish",
        phrase: "Pierdol się",
        pronunciation: "p'yer-dole sheh",
        audioFile: "audio/polish.mp3",
        memeReference: "images/polish-meme.jpg",
        funFact: "Polish has some of the most tongue-twisting profanity in Europe!"
    },
    {
        id: "greek",
        country: "Greece",
        countryCode: "GR",
        languageName: "Greek",
        phrase: "Άντε γαμήσου",
        pronunciation: "AHN-deh yah-MEE-soo",
        audioFile: "audio/greek.mp3",
        memeReference: "images/greek-meme.jpg",
        funFact: "Ancient Greeks had insults too, but modern Greek cursing is much more colorful!"
    },
    {
        id: "hebrew",
        country: "Israel",
        countryCode: "IL",
        languageName: "Hebrew",
        phrase: "לך תזדיין",
        pronunciation: "lech tizdayen",
        audioFile: "audio/hebrew.mp3",
        memeReference: "images/hebrew-meme.jpg",
        funFact: "Modern Hebrew slang and profanity evolved rapidly after the revival of the language!"
    },
    {
        id: "thai",
        country: "Thailand",
        countryCode: "TH",
        languageName: "Thai",
        phrase: "ไปให้ตายซะ",
        pronunciation: "pai hai dtaai sa",
        audioFile: "audio/thai.mp3",
        memeReference: "images/thai-meme.jpg",
        funFact: "Thai insults often involve buffalo, which is considered a stupid animal in Thai culture!"
    },
    {
        id: "vietnamese",
        country: "Vietnam",
        countryCode: "VN",
        languageName: "Vietnamese",
        phrase: "Đụ má mày",
        pronunciation: "doo ma may",
        audioFile: "audio/vietnamese.mp3",
        memeReference: "images/vietnamese-meme.jpg",
        funFact: "Vietnamese profanity often involves family members, especially mothers!"
    },
    {
        id: "norwegian",
        country: "Norway",
        countryCode: "NO",
        languageName: "Norwegian",
        phrase: "Dra til helvete",
        pronunciation: "drah till hell-veh-teh",
        audioFile: "audio/norwegian.mp3",
        memeReference: "images/norwegian-meme.jpg",
        funFact: "Norwegians are usually calm, but they can get creative with their cursing in the winter months!"
    },
    {
        id: "finnish",
        country: "Finland",
        countryCode: "FI",
        languageName: "Finnish",
        phrase: "Haista vittu",
        pronunciation: "HIGH-stah VIT-too",
        audioFile: "audio/finnish.mp3",
        memeReference: "images/finnish-meme.jpg",
        funFact: "Literally translates to 'smell a c*nt' - Finns are nothing if not direct!"
    },
    {
        id: "danish",
        country: "Denmark",
        countryCode: "DK",
        languageName: "Danish",
        phrase: "Skrid",
        pronunciation: "skree",
        audioFile: "audio/danish.mp3",
        memeReference: "images/danish-meme.jpg",
        funFact: "Danish has some surprisingly mild-sounding insults despite their Viking heritage!"
    },
    {
        id: "czech",
        country: "Czech Republic",
        countryCode: "CZ",
        languageName: "Czech",
        phrase: "Jdi do prdele",
        pronunciation: "ydi do pr-del-eh",
        audioFile: "audio/czech.mp3",
        memeReference: "images/czech-meme.jpg",
        funFact: "Czech profanity often involves animals and bodily functions!"
    },
    {
        id: "hungarian",
        country: "Hungary",
        countryCode: "HU",
        languageName: "Hungarian",
        phrase: "Bassza meg",
        pronunciation: "BAH-sah meg",
        audioFile: "audio/hungarian.mp3",
        memeReference: "images/hungarian-meme.jpg",
        funFact: "Hungarian curses are so complex they can form entire sentences of pure profanity!"
    },
    {
        id: "romanian",
        country: "Romania",
        countryCode: "RO",
        languageName: "Romanian",
        phrase: "Du-te dracu",
        pronunciation: "doo-teh drah-koo",
        audioFile: "audio/romanian.mp3",
        memeReference: "images/romanian-meme.jpg",
        funFact: "Romanian curses often involve the devil (dracu) or supernatural elements!"
    },
    {
        id: "bulgarian",
        country: "Bulgaria",
        countryCode: "BG",
        languageName: "Bulgarian",
        phrase: "Еби се",
        pronunciation: "eh-bee seh",
        audioFile: "audio/bulgarian.mp3",
        memeReference: "images/bulgarian-meme.jpg",
        funFact: "Bulgarian has some of the most creative combinations of profanity in the Slavic languages!"
    },
    {
        id: "serbian",
        country: "Serbia",
        countryCode: "RS",
        languageName: "Serbian",
        phrase: "Јеби се",
        pronunciation: "YEH-bee seh",
        audioFile: "audio/serbian.mp3",
        memeReference: "images/serbian-meme.jpg",
        funFact: "Serbian curses can be strung together to form elaborate insults that go on for sentences!"
    },
    {
        id: "croatian",
        country: "Croatia",
        countryCode: "HR",
        languageName: "Croatian",
        phrase: "Jebi se",
        pronunciation: "YEH-bee seh",
        audioFile: "audio/croatian.mp3",
        memeReference: "images/croatian-meme.jpg",
        funFact: "Croatian and Serbian share many insults, but each claims theirs are more effective!"
    },
    {
        id: "ukrainian",
        country: "Ukraine",
        countryCode: "UA",
        languageName: "Ukrainian",
        phrase: "Іди нахуй",
        pronunciation: "ee-DEE nah-KHUY",
        audioFile: "audio/ukrainian.mp3",
        memeReference: "images/ukrainian-meme.jpg",
        funFact: "This phrase became world-famous after the defiant response of Ukrainian soldiers on Snake Island!"
    },
    {
        id: "tagalog",
        country: "Philippines",
        countryCode: "PH",
        languageName: "Tagalog",
        phrase: "Putang ina mo",
        pronunciation: "poo-TANG ee-NAH moh",
        audioFile: "audio/tagalog.mp3",
        memeReference: "images/tagalog-meme.jpg",
        funFact: "This phrase literally translates to 'your mother is a whore' and is commonly shortened to 'PI' in text!"
    },
    {
        id: "indonesian",
        country: "Indonesia",
        countryCode: "ID",
        languageName: "Indonesian",
        phrase: "Ngentot",
        pronunciation: "ng-en-tot",
        audioFile: "audio/indonesian.mp3",
        memeReference: "images/indonesian-meme.jpg",
        funFact: "Indonesian profanity is heavily influenced by local dialects, especially Javanese!"
    },
    {
        id: "malay",
        country: "Malaysia",
        countryCode: "MY",
        languageName: "Malay",
        phrase: "Pergi mampos",
        pronunciation: "per-gee mam-pos",
        audioFile: "audio/malay.mp3",
        memeReference: "images/malay-meme.jpg",
        funFact: "Malay insults often involve animals, with 'babi' (pig) being particularly offensive in this Muslim country!"
    },
    {
        id: "swahili",
        country: "Kenya",
        countryCode: "KE",
        languageName: "Swahili",
        phrase: "Enda uchome",
        pronunciation: "en-dah oo-CHO-meh",
        audioFile: "audio/swahili.mp3",
        memeReference: "images/swahili-meme.jpg",
        funFact: "Swahili speakers often borrow English profanity since traditional Swahili has few native curse words!"
    },
    {
        id: "zulu",
        country: "South Africa",
        countryCode: "ZA",
        languageName: "Zulu",
        phrase: "Hamba uyosuka",
        pronunciation: "ham-bah oo-yo-soo-kah",
        audioFile: "audio/zulu.mp3",
        memeReference: "images/zulu-meme.jpg",
        funFact: "Zulu insults are often more about the tone than the actual words used!"
    },
    {
        id: "afrikaans",
        country: "South Africa",
        countryCode: "ZA",
        languageName: "Afrikaans",
        phrase: "Fok jou",
        pronunciation: "fock yo",
        audioFile: "audio/afrikaans.mp3",
        memeReference: "images/afrikaans-meme.jpg",
        funFact: "Afrikaans profanity is heavily influenced by Dutch, but has developed its own unique expressions!"
    },
    {
        id: "amharic",
        country: "Ethiopia",
        countryCode: "ET",
        languageName: "Amharic",
        phrase: "ተዋ",
        pronunciation: "te-wa",
        audioFile: "audio/amharic.mp3",
        memeReference: "images/amharic-meme.jpg",
        funFact: "Amharic speakers tend to use euphemisms rather than direct profanity!"
    },
    {
        id: "persian",
        country: "Iran",
        countryCode: "IR",
        languageName: "Persian (Farsi)",
        phrase: "گمشو",
        pronunciation: "gom-sho",
        audioFile: "audio/persian.mp3",
        memeReference: "images/persian-meme.jpg",
        funFact: "Persian poetry is famous worldwide, but Persian profanity can be just as creative!"
    },
    {
        id: "urdu",
        country: "Pakistan",
        countryCode: "PK",
        languageName: "Urdu",
        phrase: "بھاڑ میں جاؤ",
        pronunciation: "bhar mein jao",
        audioFile: "audio/urdu.mp3",
        memeReference: "images/urdu-meme.jpg",
        funFact: "Urdu and Hindi share many insults due to their common origins!"
    },
    {
        id: "bengali",
        country: "Bangladesh",
        countryCode: "BD",
        languageName: "Bengali",
        phrase: "খাংকির পোলা",
        pronunciation: "khankir pola",
        audioFile: "audio/bengali.mp3",
        memeReference: "images/bengali-meme.jpg",
        funFact: "Bengali has some of the most poetic-sounding profanity in South Asia!"
    },
    {
        id: "punjabi",
        country: "India",
        countryCode: "IN",
        languageName: "Punjabi",
        phrase: "ਤੇਰੀ ਪੈਂਚੋ",
        pronunciation: "teri pencho",
        audioFile: "audio/punjabi.mp3",
        memeReference: "images/punjabi-meme.jpg",
        funFact: "Punjabi insults are delivered with such enthusiasm they've become popular in Bollywood films!"
    },
    {
        id: "tamil",
        country: "India",
        countryCode: "IN",
        languageName: "Tamil",
        phrase: "போடா",
        pronunciation: "poda",
        audioFile: "audio/tamil.mp3",
        memeReference: "images/tamil-meme.jpg",
        funFact: "Tamil is one of the world's oldest languages, so people have been saying this for thousands of years!"
    },
    {
        id: "telugu",
        country: "India",
        countryCode: "IN",
        languageName: "Telugu",
        phrase: "దెంగేయ్",
        pronunciation: "dengey",
        audioFile: "audio/telugu.mp3",
        memeReference: "images/telugu-meme.jpg",
        funFact: "Telugu insults often involve creative combinations of animals and bodily functions!"
    },
    {
        id: "marathi",
        country: "India",
        countryCode: "IN",
        languageName: "Marathi",
        phrase: "झवाडया",
        pronunciation: "zhavadya",
        audioFile: "audio/marathi.mp3",
        memeReference: "images/marathi-meme.jpg",
        funFact: "Marathi speakers in Mumbai have developed their own unique slang and insults!"
    },
    {
        id: "gujarati",
        country: "India",
        countryCode: "IN",
        languageName: "Gujarati",
        phrase: "ગાંડ મરા",
        pronunciation: "gaand mara",
        audioFile: "audio/gujarati.mp3",
        memeReference: "images/gujarati-meme.jpg",
        funFact: "Despite Gujarat being the birthplace of Gandhi, Gujarati has some surprisingly colorful profanity!"
    },
    {
        id: "nepali",
        country: "Nepal",
        countryCode: "NP",
        languageName: "Nepali",
        phrase: "मुजी",
        pronunciation: "muji",
        audioFile: "audio/nepali.mp3",
        memeReference: "images/nepali-meme.jpg",
        funFact: "This word is so common in Nepal that tourists often learn it without realizing it's profanity!"
    },
    {
        id: "sinhalese",
        country: "Sri Lanka",
        countryCode: "LK",
        languageName: "Sinhalese",
        phrase: "හුකපන්",
        pronunciation: "huka-pan",
        audioFile: "audio/sinhalese.mp3",
        memeReference: "images/sinhalese-meme.jpg",
        funFact: "Sinhalese profanity is rarely heard in public, making it extra shocking when used!"
    },
    {
        id: "khmer",
        country: "Cambodia",
        countryCode: "KH",
        languageName: "Khmer",
        phrase: "ធ្វើម៉េចចង់",
        pronunciation: "tweu mech jong",
        audioFile: "audio/khmer.mp3",
        memeReference: "images/khmer-meme.jpg",
        funFact: "Cambodians are generally very polite, so their insults carry extra weight when used!"
    },
    {
        id: "burmese",
        country: "Myanmar",
        countryCode: "MM",
        languageName: "Burmese",
        phrase: "လီးစုပ်",
        pronunciation: "lee soak",
        audioFile: "audio/burmese.mp3",
        memeReference: "images/burmese-meme.jpg",
        funFact: "Burmese profanity often involves references to dogs, which are considered unclean!"
    },
    {
        id: "mongolian",
        country: "Mongolia",
        countryCode: "MN",
        languageName: "Mongolian",
        phrase: "Чамд хамаагүй",
        pronunciation: "chamd khamaagui",
        audioFile: "audio/mongolian.mp3",
        memeReference: "images/mongolian-meme.jpg",
        funFact: "Mongolian insults can be traced back to the time of Genghis Khan!"
    },
    {
        id: "kazakh",
        country: "Kazakhstan",
        countryCode: "KZ",
        languageName: "Kazakh",
        phrase: "Сені көрсем көтім ашиды",
        pronunciation: "seni korsem kotim ashidi",
        audioFile: "audio/kazakh.mp3",
        memeReference: "images/kazakh-meme.jpg",
        funFact: "Kazakh insults often involve camels and other steppe animals!"
    },
    {
        id: "uzbek",
        country: "Uzbekistan",
        countryCode: "UZ",
        languageName: "Uzbek",
        phrase: "Котингни йиртаман",
        pronunciation: "kotingni yirtaman",
        audioFile: "audio/uzbek.mp3",
        memeReference: "images/uzbek-meme.jpg",
        funFact: "Uzbek profanity combines influences from Persian, Turkish, and Russian traditions!"
    },
    {
        id: "azerbaijani",
        country: "Azerbaijan",
        countryCode: "AZ",
        languageName: "Azerbaijani",
        phrase: "Siktir",
        pronunciation: "sik-teer",
        audioFile: "audio/azerbaijani.mp3",
        memeReference: "images/azerbaijani-meme.jpg",
        funFact: "This word is shared with Turkish and has the same meaning in both languages!"
    },
    {
        id: "georgian",
        country: "Georgia",
        countryCode: "GE",
        languageName: "Georgian",
        phrase: "შემეცი",
        pronunciation: "shemetsi",
        audioFile: "audio/georgian.mp3",
        memeReference: "images/georgian-meme.jpg",
        funFact: "Georgian has one of the world's most unique alphabets, making their written insults look like art!"
    },
    {
        id: "armenian",
        country: "Armenia",
        countryCode: "AM",
        languageName: "Armenian",
        phrase: "Գնա գրողի ծոցը",
        pronunciation: "gna groli tsotsy",
        audioFile: "audio/armenian.mp3",
        memeReference: "images/armenian-meme.jpg",
        funFact: "Armenian is one of the oldest languages in the world, so these insults have ancient roots!"
    },
    {
        id: "albanian",
        country: "Albania",
        countryCode: "AL",
        languageName: "Albanian",
        phrase: "Qifsha ropt",
        pronunciation: "chif-sha ropt",
        audioFile: "audio/albanian.mp3",
        memeReference: "images/albanian-meme.jpg",
        funFact: "Albanian insults often involve family members and can get very creative!"
    },
    {
        id: "latvian",
        country: "Latvia",
        countryCode: "LV",
        languageName: "Latvian",
        phrase: "Ej dirst",
        pronunciation: "ey deerst",
        audioFile: "audio/latvian.mp3",
        memeReference: "images/latvian-meme.jpg",
        funFact: "Latvian profanity often involves references to the devil or supernatural beings!"
    },
    {
        id: "lithuanian",
        country: "Lithuania",
        countryCode: "LT",
        languageName: "Lithuanian",
        phrase: "Eik nahui",
        pronunciation: "eyk na-hui",
        audioFile: "audio/lithuanian.mp3",
        memeReference: "images/lithuanian-meme.jpg",
        funFact: "Lithuanian is one of the oldest Indo-European languages, with insults dating back centuries!"
    },
    {
        id: "estonian",
        country: "Estonia",
        countryCode: "EE",
        languageName: "Estonian",
        phrase: "Käi persse",
        pronunciation: "kai pers-se",
        audioFile: "audio/estonian.mp3",
        memeReference: "images/estonian-meme.jpg",
        funFact: "Estonian has borrowed many swear words from Russian and Finnish!"
    },
    {
        id: "icelandic",
        country: "Iceland",
        countryCode: "IS",
        languageName: "Icelandic",
        phrase: "Farðu til fjandans",
        pronunciation: "far-thu til fyan-dans",
        audioFile: "audio/icelandic.mp3",
        memeReference: "images/icelandic-meme.jpg",
        funFact: "Icelandic insults often involve references to trolls and other mythological creatures!"
    },
    {
        id: "irish",
        country: "Ireland",
        countryCode: "IE",
        languageName: "Irish (Gaelic)",
        phrase: "Téigh dtí diabhail",
        pronunciation: "chey dee DJOW-il",
        audioFile: "audio/irish.mp3",
        memeReference: "images/irish-meme.jpg",
        funFact: "Irish speakers often switch to English for cursing, as Gaelic lacks strong native profanity!"
    },
    {
        id: "welsh",
        country: "Wales",
        countryCode: "GB-WLS",
        languageName: "Welsh",
        phrase: "Ffyc chi",
        pronunciation: "fuck khee",
        audioFile: "audio/welsh.mp3",
        memeReference: "images/welsh-meme.jpg",
        funFact: "Welsh profanity sounds melodic even when expressing extreme anger!"
    },
    {
        id: "basque",
        country: "Spain",
        countryCode: "ES",
        languageName: "Basque",
        phrase: "Zoaz pikutara",
        pronunciation: "so-az pee-koo-tara",
        audioFile: "audio/basque.mp3",
        memeReference: "images/basque-meme.jpg",
        funFact: "Basque is a language isolate with no relation to any other language, making its profanity unique!"
    },
    {
        id: "catalan",
        country: "Spain",
        countryCode: "ES",
        languageName: "Catalan",
        phrase: "Que et fotin",
        pronunciation: "keh et foo-tin",
        audioFile: "audio/catalan.mp3",
        memeReference: "images/catalan-meme.jpg",
        funFact: "Catalans are proud of their distinct language and culture, including their unique insults!"
    },
    {
        id: "maltese",
        country: "Malta",
        countryCode: "MT",
        languageName: "Maltese",
        phrase: "Mur ħu f'għoxx ommok",
        pronunciation: "moor hoo foss om-mok",
        audioFile: "audio/maltese.mp3",
        memeReference: "images/maltese-meme.jpg",
        funFact: "Maltese is the only Semitic language written in the Latin alphabet, with Arabic-influenced profanity!"
    },
    {
        id: "luxembourgish",
        country: "Luxembourg",
        countryCode: "LU",
        languageName: "Luxembourgish",
        phrase: "Fick dech",
        pronunciation: "fick dekh",
        audioFile: "audio/luxembourgish.mp3",
        memeReference: "images/luxembourgish-meme.jpg",
        funFact: "Luxembourgers often mix French, German, and Luxembourgish when cursing for maximum effect!"
    },
    {
        id: "slovak",
        country: "Slovakia",
        countryCode: "SK",
        languageName: "Slovak",
        phrase: "Choď do riti",
        pronunciation: "khod do ri-tyi",
        audioFile: "audio/slovak.mp3",
        memeReference: "images/slovak-meme.jpg",
        funFact: "Slovak profanity is similar to Czech but with its own regional variations!"
    },
    {
        id: "slovenian",
        country: "Slovenia",
        countryCode: "SI",
        languageName: "Slovenian",
        phrase: "Jebi se",
        pronunciation: "yeh-bee seh",
        audioFile: "audio/slovenian.mp3",
        memeReference: "images/slovenian-meme.jpg",
        funFact: "Slovenian curses are often borrowed from neighboring languages but pronounced with a Slovenian accent!"
    }
];
